name: Chocolatey-AU Builds

on:
  # Trigger on pushes and on pull requests
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build on Windows
  windows-build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Build Chocolatey-AU module
      run: .\build.ps1 -Task CI -Verbose -ErrorAction Stop
    - name: Upload Windows build results
      uses: actions/upload-artifact@v4
      # Always upload build results
      if: ${{ always() }}
      with:
        name: build-results
        path: |
          code_drop/**
